# Generated by Django 2.2.7 on 2020-02-18 13:26
import os

from django.db import migrations


class Migration(migrations.Migration):
    """
    Data migration to create a superuser (per environment variables) during migrations
    when the app is booted up.

    As we intend to deploy with a docker container, this is a painless way to see our first
    superuser on any new deployment.
    """

    dependencies = [("users", "0001_initial")]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        DJANGO_DB_NAME = os.environ.get("DJANGO_DB_NAME", "default")
        DJANGO_SUPERUSER_USERNAME = os.environ.get("DJANGO_SUPERUSER_USERNAME")
        DJANGO_SUPERUSER_EMAIL = os.environ.get("DJANGO_SUPERUSER_EMAIL")
        DJANGO_SUPERUSER_PASSWORD = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

        superuser = User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=DJANGO_SUPERUSER_PASSWORD,
        )

        superuser.save()

    operations = [migrations.RunPython(generate_superuser)]
