# Generated by Django 3.0.5 on 2023-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_unit_field_on_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_tester",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has access to freshly developed features.",
                verbose_name="tester status",
            ),
        ),
    ]
