# Generated by Django 2.2.7 on 2020-03-31 16:22

from django.db import migrations, models
import django.db.models.deletion
import partaj.core.models.referral
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Primary key for the referral",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "requester",
                    models.CharField(
                        help_text="Identity of the person and service requesting the referral",
                        max_length=500,
                        verbose_name="requester",
                    ),
                ),
                (
                    "requester_email",
                    models.EmailField(
                        help_text="Email adress for the person requesting the referral",
                        max_length=254,
                        verbose_name="requester email",
                    ),
                ),
                (
                    "requester_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number for the person requesting the referral",
                        max_length=128,
                        region=None,
                        verbose_name="requester phone number",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Broad topic to help direct the referral to the appropriate office",
                        max_length=200,
                        verbose_name="subject",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Question for which you are requesting the referral",
                        verbose_name="question",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("u1", "Urgent — 1 week"),
                            ("u2", "Extremely urgent — 3 days"),
                            ("u3", "Absolute emergency — 24 hours"),
                        ],
                        help_text="Urgency level. When do you need the referral?",
                        max_length=2,
                        verbose_name="urgency",
                    ),
                ),
                (
                    "urgency_explanation",
                    models.CharField(
                        blank=True,
                        help_text="Why is this referral urgent?",
                        max_length=200,
                        verbose_name="urgency explanation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received — awaiting validation by receiver"),
                            (
                                "pending",
                                "Incomplete — more information expected from requester",
                            ),
                            ("complete", "Complete — referral in treatment"),
                            ("done", "Done — referral was answered"),
                        ],
                        default="received",
                        help_text="Current treatment status for this referral",
                        max_length=20,
                        verbose_name="referral status",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="Explain the facts and context leading to the referral",
                        verbose_name="context",
                    ),
                ),
                (
                    "prior_work",
                    models.TextField(
                        help_text="What research did you already perform before the referral?",
                        verbose_name="prior work",
                    ),
                ),
            ],
            options={"verbose_name": "referral", "db_table": "partaj_referral",},
        ),
        migrations.CreateModel(
            name="ReferralAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral attachment as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=partaj.core.models.referral.referral_attachment_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for the referral attachment, defaults to file name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral attachment",
                "db_table": "partaj_referral_attachment",
            },
        ),
    ]
