# Generated by Django 2.2.7 on 2020-02-07 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.CharField(
                        help_text="Identity of the person and service requesting the referral",
                        max_length=500,
                        verbose_name="requester",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Broad subject to help direct the referral to the appropriate office or expert",
                        max_length=200,
                        verbose_name="subject",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("u1", "Relatively urgent — 2 weeks"),
                            ("u2", "Urgent — 1 week"),
                            ("u3", "Extremely urgent — 3 days"),
                            ("u4", "Absolute emergency — 24 hours"),
                        ],
                        help_text="Urgency level",
                        max_length=2,
                        verbose_name="urgency",
                    ),
                ),
                (
                    "urgency_explanation",
                    models.CharField(
                        blank=True,
                        help_text="Why is this referral urgent? (not required for delays of 1 week or more)",
                        max_length=200,
                        verbose_name="urgency explanation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received — awaiting treatment by receiver"),
                            (
                                "pending",
                                "Pending — more information expected from requester",
                            ),
                            ("complete", "Complete — referral in treatment"),
                            ("done", "Done — referral was answered"),
                        ],
                        default="received",
                        help_text="Current treatment status for this referral",
                        max_length=20,
                        verbose_name="referral status",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="Explain the facts and context leading to the referral",
                        verbose_name="context",
                    ),
                ),
                (
                    "prior_work",
                    models.TextField(
                        help_text="What research did you already perform before the referral?",
                        verbose_name="prior work",
                    ),
                ),
            ],
            options={"verbose_name": "referral", "db_table": "partaj_referral"},
        )
    ]
