# Generated by Django 2.2.7 on 2020-04-01 15:36

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_link_user_and_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="requester_email",
            field=models.EmailField(
                blank=True,
                help_text="Email adress for the person requesting the referral",
                max_length=254,
                verbose_name="requester email",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="requester_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Phone number for the person requesting the referral",
                max_length=128,
                region=None,
                verbose_name="requester phone number",
            ),
        ),
    ]
