# Generated by Django 2.2.7 on 2020-02-26 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("core", "0002_createsuperuser")]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received — awaiting validation by receiver"),
                    (
                        "pending",
                        "Incomplete — more information expected from requester",
                    ),
                    ("complete", "Complete — referral in treatment"),
                    ("done", "Done — referral was answered"),
                ],
                default="received",
                help_text="Current treatment status for this referral",
                max_length=20,
                verbose_name="referral status",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("u1", "Relatively urgent — 2 weeks"),
                    ("u2", "Urgent — 1 week"),
                    ("u3", "Extremely urgent — 3 days"),
                    ("u4", "Absolute emergency — 24 hours"),
                ],
                help_text="Urgency level. When do you need the referral?",
                max_length=2,
                verbose_name="urgency",
            ),
        ),
        migrations.CreateModel(
            name="ReferralAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral attachment as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("file", models.FileField(upload_to="", verbose_name="file")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for the referral attachment, defaults to file name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
        ),
    ]
