# Generated by Django 2.2.7 on 2020-04-06 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_make_phone_and_email_optional_on_referral"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the unit as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human name for this unit",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
            ],
            options={"verbose_name": "unit", "db_table": "partaj_unit",},
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the topic as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this topic",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.Unit",
                        verbose_name="unit",
                    ),
                ),
            ],
            options={"verbose_name": "topic", "db_table": "partaj_topic",},
        ),
    ]
