# Generated by Django 2.2.7 on 2020-03-04 16:08

from django.db import migrations, models
import partaj.core.models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_add_referral_attachments")]

    operations = [
        migrations.AlterField(
            model_name="referralattachment",
            name="file",
            field=models.FileField(
                upload_to=partaj.core.models.referral_attachment_upload_to,
                verbose_name="file",
            ),
        )
    ]
