# Generated by Django 2.2.7 on 2020-03-09 15:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("core", "0004_update_referral_attachments_name")]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="question",
            field=models.CharField(
                default="Pre-existing referral",
                help_text="Question for which you are requesting the referral",
                max_length=200,
                verbose_name="question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referral",
            name="requester_email",
            field=models.EmailField(
                default="default@example.com",
                help_text="Email adress for the person requesting the referral",
                max_length=254,
                verbose_name="requester email",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referral",
            name="requester_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+33000000000",
                help_text="Phone number for the person requesting the referral",
                max_length=128,
                region=None,
                verbose_name="requester phone number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="referral",
            name="subject",
            field=models.CharField(
                help_text="Broad topic to help direct the referral to the appropriate office",
                max_length=200,
                verbose_name="subject",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("u1", "Urgent — 1 week"),
                    ("u2", "Extremely urgent — 3 days"),
                    ("u3", "Absolute emergency — 24 hours"),
                ],
                help_text="Urgency level. When do you need the referral?",
                max_length=2,
                verbose_name="urgency",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="urgency_explanation",
            field=models.CharField(
                blank=True,
                help_text="Why is this referral urgent?",
                max_length=200,
                verbose_name="urgency explanation",
            ),
        ),
    ]
