# Generated by Django 2.2.7 on 2020-04-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_topics_and_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Broad topic to help direct the referral to the appropriate office",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Topic",
                verbose_name="topic",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Broad topic to help direct the referral to the appropriate office",
                max_length=200,
                verbose_name="subject",
            ),
        ),
    ]
