# Generated by Django 2.2.7 on 2020-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_update_referral_for_initial_beta")]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="question",
            field=models.TextField(
                help_text="Question for which you are requesting the referral",
                verbose_name="question",
            ),
        )
    ]
