# Generated by Django 2.2.7 on 2020-04-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_link_referral_to_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Primary key for the membership",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        help_text="Role granted to the user in the unit by this membership",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit to which we're linking the user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Unit",
                        verbose_name="unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose membership is characterized",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "unit membership",
                "db_table": "partaj_unitmembership",
            },
        ),
        migrations.AddField(
            model_name="unit",
            name="members",
            field=models.ManyToManyField(
                help_text="Members of the unit",
                through="core.UnitMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
    ]
