# Generated by Django 2.2.7 on 2020-04-08 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_add_users_to_unit"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unitmembership",
            unique_together={("unit", "user")},
        ),
    ]
