# Generated by Django 2.2.7 on 2020-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_size_to_referral_attachments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReferralAssignment",
        ),
    ]
