# Generated by Django 3.0.5 on 2020-05-01 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_use_django_fsm_for_referral_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.CreateModel(
            name="ReferralAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral answer as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Actual content of the answer to the referral",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the answer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral the answer is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
        ),
    ]
