# Generated by Django 3.0.5 on 2020-05-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_create_existing_referral_activities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralattachment",
            name="referral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                related_query_name="attachments",
                to="core.Referral",
                verbose_name="referral",
            ),
        ),
    ]
