# Generated by Django 3.0.5 on 2020-06-03 11:30

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_name_referral_attachments_inverse_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("assigned", "Assigned"),
                    ("received", "Received"),
                    ("closed", "Closed"),
                    ("incomplete", "Incomplete"),
                    ("answered", "Answered"),
                ],
                default="received",
                help_text="Current treatment status for this referral",
                max_length=50,
                verbose_name="referral state",
            ),
        ),
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("answered", "answered"),
                    ("created", "created"),
                    ("unassigned", "unassigned"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
