# Generated by Django 3.0.5 on 2020-06-11 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0020_remove_legacy_requested_fields_on_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="topic",
            field=models.ForeignKey(
                help_text="Broad topic to help direct the referral to the appropriate office",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Topic",
                verbose_name="topic",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the referral",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
