# Generated by Django 3.0.5 on 2020-08-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_referral_answer_attachment_with_base_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralUrgency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Expected treatment duration", verbose_name="duration"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this urgency level is the default level for new referrals",
                        verbose_name="is default",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "requires_justification",
                    models.BooleanField(
                        help_text="Whether to require a justification when this urgency is selected",
                        verbose_name="requires justification",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral urgency",
                "db_table": "partaj_referral_urgency",
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="urgency_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Urgency level. When is the referral answer needed?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.ReferralUrgency",
                verbose_name="urgency",
            ),
        ),
    ]
