# Generated by Django 3.0.5 on 2020-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_draft_answer_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralanswer",
            name="state",
            field=models.CharField(
                choices=[("draft", "draft"), ("published", "published")],
                default="published",
                help_text="State of this referral answer",
                max_length=50,
                verbose_name="state",
            ),
        ),
    ]
