# Generated by Django 3.0.5 on 2020-09-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_add_state_field_to_referralanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralanswer",
            name="published_answer",
            field=models.OneToOneField(
                blank=True,
                help_text="published answer corresponding to this one, if it is a draft answer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_answer",
                to="core.ReferralAnswer",
                verbose_name="published answer",
            ),
        ),
    ]
