# Generated by Django 3.0.5 on 2020-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_move_answer_attachments_to_manytomany"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralanswerattachment",
            name="referral_answer",
        ),
        migrations.AlterField(
            model_name="referralanswerattachment",
            name="referral_answers",
            field=models.ManyToManyField(
                related_name="attachments",
                related_query_name="attachments",
                to="core.ReferralAnswer",
                verbose_name="referral answers",
            ),
        ),
    ]
