# Generated by Django 3.0.5 on 2021-01-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_object_field_to_referrals"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this topic is displayed in the referral form",
                verbose_name="is active",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent topic in the hierarchy of topics",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.Topic",
                verbose_name="parent",
            ),
        ),
    ]
