# Generated by Django 3.0.5 on 2021-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_create_unit_referral_relations_for_existing_referrals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("answered", "answered"),
                    ("draft_answered", "draft answered"),
                    ("created", "created"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
