# Generated by Django 3.0.5 on 2021-03-11 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partaj.core.models.attachment
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0042_add_referralactivity_verbs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral message as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Textual content of the referral message",
                        verbose_name="content",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral to which this message is related",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the referral message",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral message",
                "db_table": "partaj_referral_message",
            },
        ),
        migrations.CreateModel(
            name="ReferralMessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the attachment as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=partaj.core.models.attachment.attachment_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for the attachment, defaults to file name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True,
                        help_text="Attachment file size in bytes",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
                (
                    "referral_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        related_query_name="attachment",
                        to="core.ReferralMessage",
                        verbose_name="referral message",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral message attachment",
                "db_table": "partaj_referral_message_attachment",
            },
        ),
    ]
