# Generated by Django 3.0.5 on 2021-10-27 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0048_increase_objectfield_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("answered", "Answered"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("in_validation", "In validation"),
                    ("incomplete", "Incomplete"),
                    ("processing", "Processing"),
                    ("received", "Received"),
                ],
                default="received",
                help_text="Current treatment status for this referral",
                max_length=50,
                verbose_name="referral state",
            ),
        ),
        migrations.CreateModel(
            name="ReferralUserLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Primary key for the unit assignment",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral the user is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is attached to the referral",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral user link",
                "db_table": "partaj_referraluserlink",
                "unique_together": {("user", "referral")},
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="users",
            field=models.ManyToManyField(
                help_text="Users who are registered as requesters for this referral",
                related_name="referrals_requested",
                through="core.ReferralUserLink",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
