# Generated by Django 3.0.5 on 2022-01-26 16:25

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Set the `0` index on the existing default referral urgency. All other indices are optional
    and can be set manually in the back-office.
    """
    ReferralUrgency = apps.get_model("core", "ReferralUrgency")

    # Set the existing default as index 0
    try:
        existing_default = ReferralUrgency.objects.get(is_default=True)
        existing_default.index = 0
        existing_default.save()
    except ReferralUrgency.DoesNotExist:
        pass


def backwards(apps, schema_editor):
    """
    Just delete all user-referral relationships defined through the "users" ManyToMany.
    """
    ReferralUrgency = apps.get_model("core", "ReferralUrgency")

    try:
        existing_index_0 = ReferralUrgency.objects.get(index=0)
        existing_index_0.is_default = True
        existing_index_0.save()
    except ReferralUrgency.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_index_field_on_referral_urgencies"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
