# Generated by Django 3.0.5 on 2022-07-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_referralreport_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralreportattachment",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                related_query_name="attachments",
                to="core.ReferralReport",
                verbose_name="referral report attachments",
            ),
        ),
    ]
