# Generated by Django 3.0.5 on 2022-07-27 08:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0071_alter_referralreportattachment_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral message as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Textual content of the report message",
                        verbose_name="content",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Report to which this message is related",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.ReferralReport",
                        verbose_name="report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the referral message",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "report message",
                "db_table": "partaj_report_message",
            },
        ),
    ]
