# Generated by Django 3.0.5 on 2022-10-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralreportversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "referral report version",
            },
        ),
    ]
