# Generated by Django 3.0.5 on 2022-10-13 12:52

from django.db import migrations

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_reportmessage_update_and_requestreportvalidation"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="answer_type",
            field=django_fsm.FSMField(
                choices=[
                    ("attachment", "Attachment"),
                    ("editor", "Editor"),
                    ("closed", "None"),
                ],
                default="closed",
                help_text="referral answer type",
                max_length=50,
                verbose_name="referral answer type",
            ),
        ),
    ]
