# Generated by Django 3.0.5 on 2023-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_change_referraluserlink_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("10_n", "normal"), ("90_s", "sensible")],
                help_text="referral status.",
                max_length=20,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
