# Generated by Django 3.0.5 on 2023-03-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_referralnote_notedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="answer_properties",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="referral answer properties for export",
                max_length=200,
                null=True,
                verbose_name="referral answer properties for export",
            ),
        ),
    ]
