# Generated by Django 3.0.5 on 2023-03-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_unit_kdbaccess_and_kdbexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Brief sentence describing the title of the referral",
                max_length=60,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="html",
            field=models.TextField(
                help_text="Html generated from document file or editor",
                verbose_name="html",
            ),
        ),
    ]
