# Generated by Django 3.0.5 on 2023-05-15 14:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_add_activity_update_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralnote",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("received", "Received"),
                    ("to_send", "To send"),
                    ("active", "Active"),
                    ("to_delete", "To delete"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                default="received",
                help_text="Status indicating action to do for scheduled tasks",
                max_length=50,
                verbose_name="ReferralNote state",
            ),
        ),
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_requester", "added requester"),
                    ("added_observer", "added observer"),
                    ("answered", "answered"),
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("closed", "closed"),
                    ("created", "created"),
                    ("draft_answered", "draft answered"),
                    ("removed_requester", "removed requester"),
                    ("removed_observer", "removed observer"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("urgencylevel_changed", "urgency level changed"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                    ("version_added", "version added"),
                    ("updated_title", "updated title"),
                    ("topic_updated", "topic updated"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="assigned_units_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), size=None
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="author",
            field=models.CharField(
                help_text="Full author note name", max_length=255, verbose_name="author"
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="html",
            field=models.TextField(
                blank=True,
                help_text="Html generated from document file or editor",
                null=True,
                verbose_name="html",
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="requesters_unit_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), size=None
            ),
        ),
        migrations.AlterField(
            model_name="referralnote",
            name="topic",
            field=models.CharField(
                help_text="Referral topic title", max_length=255, verbose_name="topic"
            ),
        ),
        migrations.AlterField(
            model_name="referraltopichistory",
            name="referral",
            field=models.ForeignKey(
                help_text="Referral topic change activity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_topic_history",
                to="core.Referral",
                verbose_name="referral",
            ),
        ),
    ]
