# Generated by Django 3.0.5 on 2023-05-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_referralnote_state"),
    ]

    operations = [migrations.RenameModel("ReportMessage", "ReportEvent")]
