# Generated by Django 3.0.5 on 2023-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_referralnote_contributors"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmetadata",
            name="sender_unit_name",
            field=models.CharField(
                blank=True,
                help_text="unit name the user is from",
                max_length=200,
                null=True,
                verbose_name="sender unit name",
            ),
        ),
        migrations.AddField(
            model_name="reportevent",
            name="timestamp",
            field=models.IntegerField(
                help_text="Timestamp used to fuse event at display",
                null=True,
                verbose_name="timestamp",
            ),
        ),
    ]
