# Generated by Django 3.0.5 on 2024-05-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_add_scan_properties_to_all_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notedocument",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
        migrations.AlterField(
            model_name="referralanswerattachment",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
        migrations.AlterField(
            model_name="referralattachment",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
        migrations.AlterField(
            model_name="referralmessageattachment",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
        migrations.AlterField(
            model_name="referralreportattachment",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
        migrations.AlterField(
            model_name="versiondocument",
            name="scan_id",
            field=models.CharField(
                blank=True,
                help_text="Id provided by the file scanner server",
                max_length=200,
                null=True,
                verbose_name="scan_id",
            ),
        ),
    ]
