# Generated by Django 3.0.5 on 2024-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_referral_has_prior_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='no_prior_work_justification',
            field=models.TextField(blank=True, help_text='Justification when decentralised unit did not have already made preliminary work', null=True, verbose_name='no prior work justification'),
        ),
    ]
