# Generated by Django 3.0.5 on 2025-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_referral_no_prior_work_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="member_role_access",
            field=models.CharField(
                choices=[
                    ("total", "All referrals"),
                    ("restricted", "No access to received referrals"),
                ],
                default="total",
                help_text="Referral access restriction for unit member role",
                max_length=200,
                verbose_name="receiver unit role",
            ),
        ),
    ]
