# Generated by Django 3.0.5 on 2025-03-24 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_unit_member_role_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral subdivision as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral group",
                "db_table": "partaj_referral_group",
            },
        ),
        migrations.AlterField(
            model_name="unit",
            name="member_role_access",
            field=models.CharField(
                choices=[
                    ("total", "All referrals"),
                    ("restricted", "No access to received referrals"),
                ],
                default="total",
                help_text="Referral access restriction for unit member role",
                max_length=200,
                verbose_name="member role access",
            ),
        ),
        migrations.CreateModel(
            name="ReferralSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral section as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("main", "Main"), ("secondary", "Secondary")],
                        default="main",
                        max_length=64,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referral group section",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="core.ReferralGroup",
                        verbose_name="subdivision",
                    ),
                ),
                (
                    "referral",
                    models.OneToOneField(
                        help_text="The referral link to this section",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral group section",
                "db_table": "partaj_referral_group_section",
            },
        ),
    ]
