# Generated by Django 3.0.5 on 2025-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_referral_activity_verb_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_requester", "added requester"),
                    ("added_observer", "added observer"),
                    ("answered", "answered"),
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("closed", "closed"),
                    ("created", "created"),
                    ("draft_answered", "draft answered"),
                    ("removed_requester", "removed requester"),
                    ("removed_observer", "removed observer"),
                    ("subreferral_created", "subreferral created"),
                    ("reopened", "reopened"),
                    ("subreferral_confirmed", "subreferral confirmed"),
                    ("subtitle_updated", "subtitle updated"),
                    ("subquestion_updated", "subquestion updated"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("urgencylevel_changed", "urgency level changed"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                    ("version_added", "version added"),
                    ("updated_title", "updated title"),
                    ("topic_updated", "topic updated"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
