# Generated by Django 3.0.5 on 2025-08-17 07:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0119_referral_activity_verb_update_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralReportPublishment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the report publishment as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Report the publishment is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publishments",
                        to="core.ReferralReport",
                        verbose_name="report",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        blank=True,
                        help_text="The version attached to the report version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ReferralReportVersion",
                        verbose_name="report version",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral report publishment",
                "db_table": "partaj_referral_report_publishment",
                "ordering": ["-created_at"],
            },
        ),
    ]
