# Generated by Django 3.0.5 on 2025-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_referralreportpublishment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralreportpublishment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="referralreportpublishment",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="publishment comment",
            ),
        ),
    ]
