# Generated by Django 3.0.5 on 2025-10-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_reopening_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralreportpublishment',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment at report sending', null=True, verbose_name='publishment comment'),
        ),
    ]
