# Generated by Django 3.0.5 on 2025-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_referral_relationships"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="default_send_to_knowledge_base",
            field=models.BooleanField(
                blank=True,
                help_text="Should this referral be sent to the knowledge base by default",
                null=True,
                verbose_name="default send to knowledge base",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="override_send_to_knowledge_base",
            field=models.BooleanField(
                blank=True,
                help_text="Override the default send to knowledge base field",
                null=True,
                verbose_name="override send to knowledge base",
            ),
        ),
    ]
