# Generated by Django 4.2.27 on 2026-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralreportappendix",
            name="include_to_publishment",
            field=models.BooleanField(
                default=False,
                help_text="Should include this appendix to the publishment",
                verbose_name="Include appendix",
            ),
        ),
    ]
