# Generated by Django 4.2.29 on 2026-04-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_referralreportpublishment_appendices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralReminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("draft_reminder", "Draft reminder")], max_length=50
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral reminder",
                "db_table": "partaj_referral_reminder",
                "unique_together": {("referral", "type")},
            },
        ),
    ]
