# Generated by Django 5.2.13 on 2026-04-09 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_referralreportpublishment_appendices_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralanswervalidationrequest",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referralassignment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referralrelationship",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referralunitassignment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referraluserlink",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="unitmembership",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="referral",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partaj users that have been assigned to work on this referral",
                null=True,
                related_name="referrals_assigned",
                through="core.ReferralAssignment",
                through_fields=("referral", "assignee"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignees",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="relationships",
            field=models.ManyToManyField(
                help_text="Referrals related with this referral",
                related_name="referrals_related_with",
                through="core.ReferralRelationship",
                through_fields=("main_referral", "related_referral"),
                to="core.referral",
                verbose_name="relationship",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="units",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partaj units that have been assigned to this referral",
                null=True,
                related_name="referrals_assigned",
                through="core.ReferralUnitAssignment",
                through_fields=("referral", "unit"),
                to="core.unit",
                verbose_name="units",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are registered as requesters for this referral",
                null=True,
                related_name="referrals_requested",
                through="core.ReferralUserLink",
                through_fields=("referral", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
        migrations.AlterField(
            model_name="referralsatisfaction",
            name="choice",
            field=models.IntegerField(
                choices=[
                    (10, "satisfaction happy choice"),
                    (5, "satisfaction normal choice"),
                    (0, "satisfaction unhappy choice"),
                ],
                help_text="Choice made for the satisfaction request",
                verbose_name="choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="referralanswervalidationrequest",
            constraint=models.UniqueConstraint(
                fields=("answer", "validator"), name="unique_answer_validator_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralassignment",
            constraint=models.UniqueConstraint(
                fields=("assignee", "referral"),
                name="unique_assignee_referral_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="referralrelationship",
            constraint=models.UniqueConstraint(
                fields=("main_referral", "related_referral"),
                name="unique_main_related_referral",
            ),
        ),
        migrations.AddConstraint(
            model_name="referralunitassignment",
            constraint=models.UniqueConstraint(
                fields=("unit", "referral"), name="unique_unit_referral_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="referraluserlink",
            constraint=models.UniqueConstraint(
                fields=("user", "referral"), name="unique_user_referral_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitmembership",
            constraint=models.UniqueConstraint(
                fields=("unit", "user"), name="unique_unit_user_membership"
            ),
        ),
    ]
