# Generated by Django 2.2.7 on 2020-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_referral_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralattachment",
            name="size",
            field=models.IntegerField(
                blank=True,
                help_text="Attachment file size in bytes",
                null=True,
                verbose_name="file size",
            ),
        ),
    ]
