# Generated by Django 3.0.5 on 2020-05-20 13:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_add_referral_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral activity as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("assigned", "assigned"),
                            ("answered", "answered"),
                            ("created", "created"),
                        ],
                        help_text="Verb expressing the action this activity represents",
                        max_length=50,
                        verbose_name="verb",
                    ),
                ),
                (
                    "item_object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the linked item",
                        max_length=255,
                        verbose_name="item object id",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_activity",
                        related_query_name="referral_activity",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "item_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model for the linked item",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="item content type",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral on which the activity took place",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        related_query_name="activity",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
        ),
    ]
