# Generated by Django 3.0.5 on 2020-06-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_update_models_for_unassign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="requester_email",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="requester_phone_number",
        ),
    ]
