# Generated by Django 3.0.5 on 2020-05-20 13:25

from datetime import timedelta

from django.db import migrations
from django.utils import translation


def forwards(apps, schema_editor):
    """
    Create ReferralUrgency objects for each existing urgency. Then, for each Referral,
    map its urgency field to the relevant ReferralUrgency.
    """

    Referral = apps.get_model("core", "Referral")
    ReferralUrgency = apps.get_model("core", "ReferralUrgency")

    # Create all the previously existing hardcoded urgencies
    translation.activate("en")
    urgencies = {
        "u1": ReferralUrgency.objects.create(
            duration=timedelta(days=7),
            name="Urgent — 1 week",
            requires_justification=True,
        ),
        "u2": ReferralUrgency.objects.create(
            duration=timedelta(days=3),
            name="Extremely urgent — 3 days",
            requires_justification=True,
        ),
        "u3": ReferralUrgency.objects.create(
            duration=timedelta(days=1),
            name="Absolute emergency — 24 hours",
            requires_justification=True,
        ),
    }

    # Add a default urgency level matching current practice
    default_urgency = ReferralUrgency.objects.create(
        duration=timedelta(days=21),
        name="3 weeks",
        requires_justification=False,
        is_default=True,
    )

    for referral in Referral.objects.all():
        referral.urgency_level = (
            default_urgency if not referral.urgency else urgencies[referral.urgency]
        )
        referral.save()


def backwards(apps, schema_editor):
    """
    Remove all ReferralUrgency objects and empty the `urgency_level` field on all referrals.
    """

    Referral = apps.get_model("core", "Referral")
    ReferralUrgency = apps.get_model("core", "ReferralUrgency")

    for referral in Referral.objects.all():
        referral.urgency_level = None
        referral.save()

    ReferralUrgency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_urgency_model"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
