# Generated by Django 3.0.5 on 2020-09-24 12:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_enable_answer_validations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralAnswerValidationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral answer validation response as uuid",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_validated", "not validated"),
                            ("pending", "pending"),
                            ("validated", "validated"),
                        ],
                        help_text="State of the validation",
                        max_length=20,
                        verbose_name="state",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Comment associated with the validation acceptance or refusal",
                        verbose_name="comment",
                    ),
                ),
                (
                    "validation_request",
                    models.OneToOneField(
                        help_text="Validation request for which this response is providing an answer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="core.ReferralAnswerValidationRequest",
                        verbose_name="validation request",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral answer validation response",
                "db_table": "partaj_referral_answer_validation_response",
            },
        ),
    ]
