# Generated by Django 3.0.5 on 2020-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_make_answer_validations_unique_by_validator"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="object",
            field=models.CharField(
                blank=True,
                help_text="Brief sentence describing the object of the referral",
                max_length=50,
                verbose_name="object",
            ),
        ),
    ]
