# Generated by Django 3.0.5 on 2021-05-26 12:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_referral_message_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("answered", "answered"),
                    ("draft_answered", "draft answered"),
                    ("created", "created"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                    ("urgencylevel_changed", "urgency level changed"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
        migrations.CreateModel(
            name="ReferralUrgencyLevelHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral urgency level history as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="explanation of new urgency level",
                        verbose_name="explanation",
                    ),
                ),
                (
                    "new_referral_urgency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.ReferralUrgency",
                        verbose_name="new urgency level",
                    ),
                ),
                (
                    "old_referral_urgency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.ReferralUrgency",
                        verbose_name="old urgency level",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral subject to the urgency level change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgencylevel_history",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral urgency level history",
                "db_table": "partaj_referral_urgency_history",
            },
        ),
    ]
