# Generated by Django 3.0.5 on 2021-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_add_urgencylevel_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralactivity",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="message field for activity verbs that do not have a linked object",
                null=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("answered", "answered"),
                    ("draft_answered", "draft answered"),
                    ("created", "created"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                    ("urgencylevel_changed", "urgency level changed"),
                    ("closed", "closed"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
