# Generated by Django 3.0.5 on 2021-09-15 09:37

from django.db import migrations

from partaj.core.models import ReferralAnswerState


def forwards(apps, schema_editor):
    """
    We just added new possible states for referrals. Some of those determine what tasks
    are available for users. Therefore we need to update existing referrals to these new
    states to make sure no referral ends up in a broken state.
    """
    ReferralAnswer = apps.get_model("core", "ReferralAnswer")

    for published_answer in ReferralAnswer.objects.filter(
        state=ReferralAnswerState.PUBLISHED
    ):
        if hasattr(published_answer, "draft_answer"):
            for attachment in published_answer.draft_answer.attachments.all():
                attachment.referral_answers.add(published_answer)
                attachment.save()


def backwards(apps, schema_editor):
    """
    Backwards is a no-op as we're repairing relationships that should have existed all along.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_update_existing_referrals_states"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
