# Generated by Django 3.0.5 on 2021-11-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0050_add_existing_referral_user_to_manytomany"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="requester",
        ),
        migrations.AlterField(
            model_name="referral",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the referral",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
