# Generated by Django 3.0.5 on 2021-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_legacy_referral_requester_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_requester", "added requester"),
                    ("answered", "answered"),
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("closed", "closed"),
                    ("created", "created"),
                    ("draft_answered", "draft answered"),
                    ("removed_requester", "removed requester"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("urgencylevel_changed", "urgency level changed"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
