# Generated by Django 3.0.5 on 2022-01-27 15:21

from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_set_index_on_existing_referral_urgencies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralurgency",
            name="is_default",
        ),
        migrations.AlterField(
            model_name="referral",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
        ),
    ]
