# Generated by Django 3.0.5 on 2022-05-20 15:22

from django.db import migrations

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_remove_is_default_on_referralurgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("answered", "Answered"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("in_validation", "In validation"),
                    ("incomplete", "Incomplete"),
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("received", "Received"),
                ],
                default="draft",
                help_text="Current treatment status for this referral",
                max_length=50,
                verbose_name="referral state",
            ),
        ),
    ]
