# Generated by Django 3.0.5 on 2022-06-20 14:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral report as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        help_text="State of this referral answer",
                        max_length=50,
                        verbose_name="state",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral the report is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral report",
                "db_table": "partaj_referral_report",
            },
        ),
    ]
