# Generated by Django 3.0.5 on 2022-07-06 18:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_add_version_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the token as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="access token",
                        max_length=4096,
                        null=True,
                        verbose_name="access token",
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        help_text="refresh token",
                        max_length=4096,
                        null=True,
                        verbose_name="refresh token",
                    ),
                ),
            ],
        ),
    ]
