# Generated by Django 3.0.5 on 2022-07-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_alter_version_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"verbose_name": "token"},
        ),
        migrations.AlterModelTable(
            name="token",
            table="partaj_token",
        ),
    ]
