# Generated by Django 3.0.5 on 2022-07-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_alter_table_name_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versiondocument",
            options={"verbose_name": "referral version document"},
        ),
        migrations.AlterModelTable(
            name="versiondocument",
            table="partaj_referral_version_document",
        ),
    ]
