# Generated by Django 3.0.5 on 2023-02-28 09:55

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import partaj.core.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_referral_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the attachment as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=partaj.core.models.attachment.attachment_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for the attachment, defaults to file name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True,
                        help_text="Attachment file size in bytes",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral note document",
                "db_table": "partaj_referral_note_document",
            },
        ),
        migrations.CreateModel(
            name="ReferralNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the note as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "referral_id",
                    models.CharField(
                        help_text="ID of the referral when note is generated",
                        max_length=10,
                        verbose_name="referral id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "publication_date",
                    models.DateTimeField(verbose_name="publication date"),
                ),
                (
                    "object",
                    models.CharField(
                        help_text="Brief sentence describing the object of the referral",
                        max_length=60,
                        verbose_name="object",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Referral topic title",
                        max_length=200,
                        verbose_name="topic",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Full author note name",
                        max_length=200,
                        verbose_name="author",
                    ),
                ),
                (
                    "requesters_unit_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                (
                    "assigned_units_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Raw text from document file or editor",
                        verbose_name="version text",
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        help_text="Html generated from document file or editor",
                        verbose_name="report comment",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        help_text="The document attached to the note",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.NoteDocument",
                        verbose_name="referral note document",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral note",
                "db_table": "partaj_referral_note",
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="note",
            field=models.OneToOneField(
                blank=True,
                help_text="The referral unit note",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.ReferralNote",
                verbose_name="note",
            ),
        ),
    ]
