# Generated by Django 3.0.5 on 2023-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_referralnote_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="requester_unit_contact",
            field=models.CharField(
                default="", max_length=255, verbose_name="requester unit contact"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="requester_unit_type",
            field=models.CharField(
                choices=[
                    ("decentralised_unit", "Decentralised Unit"),
                    ("central_unit", "Central Unit"),
                ],
                default="central_unit",
                max_length=255,
                verbose_name="type",
            ),
        ),
    ]
