# Generated by Django 3.0.5 on 2023-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_reportevent_timestamp__eventmetadata_unitname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REFERRAL_MESSAGE", "Referral Message"),
                    ("REPORT_MESSAGE_NOTIFICATION", "Report Message"),
                    ("VERSION_REQUEST_VALIDATION", "Version Request Validation"),
                    ("VERSION_REQUEST_CHANGE", "Version Request Change"),
                    ("VERSION_VALIDATED", "Version Validated"),
                ],
                max_length=48,
            ),
        ),
    ]
