# Generated by Django 3.0.5 on 2024-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_metadata_receiver_unit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportevent",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "active event"),
                    ("obsolete", "obsolete event"),
                    ("inactive", "inactive event"),
                ],
                default="active",
                help_text="Event state for display purpose",
                max_length=50,
                verbose_name="state",
            ),
        ),
    ]
