# Generated by Django 3.0.5 on 2025-04-29 17:18

import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_referralgroupsection_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("answered", "Answered"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("in_validation", "In validation"),
                    ("incomplete", "Incomplete"),
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("received", "Received"),
                    ("splitting", "Splitting"),
                    ("received_splitting", "Received Splitting"),
                ],
                default="draft",
                help_text="Current treatment status for this referral",
                max_length=50,
                verbose_name="referral state",
            ),
        ),
        migrations.AlterField(
            model_name="referralsection",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Referral group section",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.ReferralGroup",
                verbose_name="subdivision",
            ),
        ),
    ]
