# Generated by Django 3.0.5 on 2025-06-19 14:57

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_subtitle_subquestion_referral_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("answered", "Answered"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("in_validation", "In validation"),
                    ("incomplete", "Incomplete"),
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("received", "Received"),
                    ("splitting", "Splitting"),
                    ("received_splitting", "Received Splitting"),
                    ("received_visible", "Received visible"),
                ],
                default="draft",
                help_text="Current treatment status for this referral",
                max_length=50,
                verbose_name="referral state",
            ),
        ),
        migrations.AlterField(
            model_name="referralactivity",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_requester", "added requester"),
                    ("added_observer", "added observer"),
                    ("answered", "answered"),
                    ("assigned", "assigned"),
                    ("assigned_unit", "assigned unit"),
                    ("closed", "closed"),
                    ("created", "created"),
                    ("draft_answered", "draft answered"),
                    ("removed_requester", "removed requester"),
                    ("removed_observer", "removed observer"),
                    ("subreferral_created", "subreferral created"),
                    ("subreferral_confirmed", "subreferral confirmed"),
                    ("unassigned", "unassigned"),
                    ("unassigned_unit", "unassigned unit"),
                    ("urgencylevel_changed", "urgency level changed"),
                    ("validated", "validated"),
                    ("validation_denied", "validation denied"),
                    ("validation_requested", "validation requested"),
                    ("version_added", "version added"),
                    ("updated_title", "updated title"),
                    ("topic_updated", "topic updated"),
                ],
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
        migrations.CreateModel(
            name="SubReferralCreatedHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral sub referral created history as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "main_referral_id",
                    models.TextField(
                        help_text="referral parent which sub referral is created from",
                        verbose_name="main referral id",
                    ),
                ),
                (
                    "secondary_referral_id",
                    models.TextField(
                        help_text="newly created id secondary referral ",
                        verbose_name="main referral id",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral subject to the sub referral created",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_subreferral_created_history",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral subreferral created history",
                "db_table": "partaj_subreferral_created_history",
            },
        ),
        migrations.CreateModel(
            name="SubReferralConfirmedHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral sub referral created history as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "main_referral_id",
                    models.TextField(
                        help_text="referral parent which sub referral is created from",
                        verbose_name="main referral id",
                    ),
                ),
                (
                    "secondary_referral_id",
                    models.TextField(
                        help_text="newly confirmed id subreferral ",
                        verbose_name="main referral id",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral subject to the sub referral confirmed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_subreferral_confirmed_history",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral subreferral confirmed history",
                "db_table": "partaj_subreferral_confirmed_history",
            },
        ),
        migrations.CreateModel(
            name="ReferralSubTitleUpdateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral sub title history as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        help_text="new referral's subtitle", verbose_name="new subtitle"
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral subject to the sub title change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_subtitle_history",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral subtitle update history",
                "db_table": "partaj_referral_subtitle_update_history",
            },
        ),
        migrations.CreateModel(
            name="ReferralSubQuestionUpdateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the referral sub question history as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "subquestion",
                    models.TextField(
                        help_text="new referral's subquestion",
                        verbose_name="new subquestion",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral subject to the sub question change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_subquestion_history",
                        to="core.Referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral subquestion history",
                "db_table": "partaj_referral_subquestion_history",
            },
        ),
    ]
