# Generated by Django 3.0.5 on 2025-08-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_publishment_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralreportpublishment",
            name="version",
            field=models.ForeignKey(
                help_text="Version the publishment is linked with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishments",
                to="core.ReferralReportVersion",
                verbose_name="publishment version",
            ),
        ),
    ]
