# Generated by Django 4.2.29 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0129_referralreportappendix_include_to_publishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralreportpublishment",
            name="appendices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Appendix at report publishment event",
                null=True,
                related_name="publishment",
                to="core.referralreportappendix",
                verbose_name="publishment appendices",
            ),
        ),
        migrations.AlterField(
            model_name="reportevent",
            name="verb",
            field=models.CharField(
                choices=[
                    ("message", "report message"),
                    ("request_validation", "report validation request"),
                    ("request_change", "report change request"),
                    (
                        "appendix_request_validation",
                        "appendix report validation request",
                    ),
                    ("appendix_request_change", "appendix report change request"),
                    ("version_added", "report version added"),
                    ("version_updated", "report version updated"),
                    ("version_validated", "report version validated"),
                    ("appendix_added", "report appendix added"),
                    ("appendix_updated", "report appendix updated"),
                    ("appendix_validated", "report appendix validated"),
                    ("knowledge_base_send_update", "knowledge base send change"),
                    ("knowledge_base_send_override", "knowledge base send override"),
                ],
                default="message",
                help_text="Verb expressing the action this activity represents",
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
