name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src/backend

env:
  DJANGO_CONFIGURATION: "Test"
  DJANGO_PARTAJ_PRIMARY_LOCATION: "https://partaj"
  DJANGO_SECRET_KEY: "TestSecretKey"
  DJANGO_SETTINGS_MODULE: "partaj.settings"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
  DJANGO_SUPERUSER_PASSWORD: "admin"

jobs:
  lint-black:
    runs-on: ubuntu-latest
    container: python:3.7-stretch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y gettext
    - name: Install python dependencies
      run: pip install .[dev]
    - name: Run black in check mode
      run: black --check partaj
  lint-flake8:
    runs-on: ubuntu-latest
    container: python:3.7-stretch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y gettext
    - name: Install python dependencies
      run: pip install .[dev]
    - name: Run flake8
      run: flake8 partaj
  lint-pylint:
    runs-on: ubuntu-latest
    container: python:3.7-stretch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y gettext
    - name: Install python dependencies
      run: pip install .[dev]
    - name: Run pylint
      run: pylint --rcfile=.pylintrc partaj
  lint-isort:
    runs-on: ubuntu-latest
    container: python:3.7-stretch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y gettext
    - name: Install python dependencies
      run: pip install .[dev]
    - name: Run isort in check mode
      run: isort --check-only partaj
  test:
    runs-on: ubuntu-latest
    container: python:3.7-stretch
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_DB: partaj
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y gettext
    - name: Install python dependencies
      run: pip install .[dev]
    - name: Get translations
      run: python manage.py compilemessages
    - name: Run our test suite
      run: pytest
      env:
        POSTGRES_HOST: postgres
